/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DESIGN.items;

import DATABASE.DataControl;
import DESIGN.Admin;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author canti
 */
public class Users extends javax.swing.JPanel {
    private boolean isEdit = false;

    public Users(String id, String name, String role, Admin referrence) {
        this.id = id;
        this.name = name;
        this.role = role;
        this.ref = referrence;
        initComponents();
    }
    String id;
    String name;
    String role;
    Admin ref;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myID = new javax.swing.JLabel();
        username = new javax.swing.JTextField(name);
        myrolee = new javax.swing.JTextField(role);
        editBtn = new DESIGN.items.MyButton();
        dltBtn = new DESIGN.items.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(524, 61));
        setMinimumSize(new java.awt.Dimension(524, 61));

        myID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        myID.setForeground(new java.awt.Color(0, 0, 0));
        myID.setText("ID: "+ id);

        username.setEditable(false);
        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        myrolee.setEditable(false);
        myrolee.setBackground(new java.awt.Color(255, 255, 255));
        myrolee.setForeground(new java.awt.Color(0, 0, 0));
        myrolee.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Role", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        editBtn.setForeground(new java.awt.Color(0, 0, 0));
        editBtn.setText("Edit");
        editBtn.setBase(new java.awt.Color(102, 255, 102));
        editBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editBtn.setRadius(12);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        dltBtn.setForeground(new java.awt.Color(0, 0, 0));
        dltBtn.setText("Delete");
        dltBtn.setBase(new java.awt.Color(255, 0, 0));
        dltBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dltBtn.setHover(new java.awt.Color(255, 153, 153));
        dltBtn.setRadius(12);
        dltBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(myID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myrolee, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(dltBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myrolee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dltBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        try (DataControl dc = new DataControl()) {
            if (isEdit) {
                isEdit = false;
                String myname = username.getText();
                String mypass = myrolee.getText();
                dc.updateUser(id, myname, mypass);
                editBtn.setText("Edit");
                ref.showAccount();
                username.setEditable(false);
                myrolee.setEditable(false);
            } else {
                isEdit = true;
                username.setEditable(true);
                myrolee.setEditable(true);
                editBtn.setText("Apply");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_editBtnActionPerformed

    private void dltBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltBtnActionPerformed
        try (DataControl dc = new DataControl()) {
            dc.deleteUser(id);
            ref.showAccount();
        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dltBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DESIGN.items.MyButton dltBtn;
    private DESIGN.items.MyButton editBtn;
    private javax.swing.JLabel myID;
    private javax.swing.JTextField myrolee;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
